---
title: "Plan 372 hw6"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
```

```{r}
tree_data <- read.csv("C:/Users/lucas/Documents/plan372/PLAN372-HW6/TS3_Raw_tree_data.csv")
```

```{r}
tree_data <- tree_data |>
  mutate(CityName = str_extract(City, "^[^,]+"),
         StateAbbr = str_extract(City, "(?<=,\\s)[A-Z]{2}$"))
```

```{r}
head(tree_data)
```

```{r}
state_counts <- table(tree_data$StateAbbr)
```

```{r}
print(state_counts)
```

```{r}
barplot(state_counts, main = "Num Records by State", xlab = "State", ylab= "Num of Records")
```

```{r}
tree_data_nc_sc <- tree_data |>
  filter(StateAbbr %in% c("NC", "SC"))
```

```{r}
cities_nc_sc <- unique(tree_data_nc_sc$CityName)
```

```{r}
print(cities_nc_sc)
```

```{r}
tree_data_nc_sc <- tree_data_nc_sc |>
  mutate(Genus = str_extract(ScientificName, "^[^ ]+"))
```

```{r}
colnames(tree_data_nc_sc)
```

```{r}
genus_avg_canopy_diameter <- tree_data_nc_sc |>
  group_by(Genus) |>
  summarize(AvgCdia = mean(AvgCdia..m., na.rm = TRUE))
```

```{r}
largest_crown_genus <- genus_avg_canopy_diameter |>
  filter(AvgCdia == max(AvgCdia))
```

```{r}
print(paste("The genus with the largest crown diameter in NC and SC is", largest_crown_genus$Genus, "with an average diameter of", largest_crown_genus$AvgCdia, "meters."))
```

Link to github repository: <https://github.com/LucasWMayo/Plan372_HW6>
